---
- name: Copy WAR file to Tomcat
  hosts: your_tomcat_host
  become: true
  tasks:
    - name: Copy WAR file from Maven build directory to Tomcat webapps
      copy:
        src: target/devops-app.war 
        dest: /opt/tomcat/webapps
        remote_src: yes
    - name: Stop Tomcat
      shell: /opt/tomcat/bin/shutdown.sh
      ignore_errors: yes
    - name: Start Tomcat
      shell: /opt/tomcat/bin/startup.sh
